package io.moonman.emergingtechnology.helpers.machines.classes;

/**
 * A packet containing performance boosts for machines. Generated by nearby Optimisers
 */
public class OptimiserPacket {
    public int energyModifier;
    public int fluidModifier;
    public int gasModifier;
    public int progressModifier;

    public OptimiserPacket() {
        energyModifier = 1;
        fluidModifier = 1;
        progressModifier = 1;
        gasModifier = 1;
    }

    public OptimiserPacket(int energy, int fluid, int gas, int progress) {
        energyModifier = energy;
        fluidModifier = fluid;
        progressModifier = progress;
        gasModifier = gas;
    }

    public int calculateEnergyUse(int value) {
        return value / energyModifier;
    }

    public int calculateFluidUse(int value) {
        return value / fluidModifier;
    }

    public int calculateProgress(int value) {
        return value / progressModifier;
    }

    public int calculateGasUse(int value) {
        return value / gasModifier;
    }

    public void reset() {
        energyModifier = 1;
        fluidModifier = 1;
        progressModifier = 1;
        gasModifier = 1;
    }
}