package io.moonman.emergingtechnology.helpers.machines.classes;

/**
 * A packet containing performance boosts for machines. Generated by nearby Optimisers
 */
public class OptimiserPacket {

    private final int DEFAULT_VALUE = 0;

    public int energyModifier;
    public int fluidModifier;
    public int gasModifier;
    public int progressModifier;

    public OptimiserPacket() {
        reset();
    }

    public OptimiserPacket(int energy, int fluid, int gas, int progress) {
        energyModifier = energy;
        fluidModifier = fluid;
        progressModifier = progress;
        gasModifier = gas;
    }

    public int calculateEnergyUse(int value) {
        return energyModifier > 0 ? value / energyModifier : value;
    }

    public int calculateFluidUse(int value) {
        return fluidModifier > 0 ? value / fluidModifier : value;
    }

    public int calculateProgress(int value) {
        return progressModifier > 0 ? value / progressModifier : value;
    }

    public int calculateGasUse(int value) {
        return gasModifier > 0 ? value / gasModifier : value;
    }

    public void reset() {
        energyModifier = DEFAULT_VALUE;
        fluidModifier = DEFAULT_VALUE;
        progressModifier = DEFAULT_VALUE;
        gasModifier = DEFAULT_VALUE;
    }

    public OptimiserPacket merge(OptimiserPacket packetToMerge) {
        this.energyModifier = packetToMerge.energyModifier > this.energyModifier ? packetToMerge.energyModifier : this.energyModifier;
        this.fluidModifier = packetToMerge.fluidModifier > this.fluidModifier ? packetToMerge.energyModifier : this.fluidModifier;
        this.progressModifier = packetToMerge.progressModifier > this.progressModifier ? packetToMerge.progressModifier : this.progressModifier;
        this.gasModifier = packetToMerge.gasModifier > this.gasModifier ? packetToMerge.gasModifier : this.gasModifier;

        return this;
    }
}